const forumTexter = [
  "Han var väl egentligen ytter men förädlades perfekt till anfallare?",
  "Klassisk grovjobbare, typ en bra Thelin?",
  "Jösses, HR scoutade alltså denna själv.",
  "Vad har han egentligen visat?",
  "Vi har sett hans maxnivå redan. Det är detta.",
  "Han hade varit värd 100 miljoner om han var 19.",
  "Tack för kaffet",
  "Men det var du som sa det. Inte jag.",
  "Hade ju en funktion väldigt väl i Peking under Rydström.",
  "Men lovar ju gott",
  "Väloljat maskineri på alla nivåer",
  "Lite nyfiken på vad det är som får dig att känna så?",
  "Omöjligt att säga, men känns rimligt.",
  "Enligt honom själv inte varit i kontakt med MFF.",
  "Det här är såklart påhitt",
  "Som vanligt duckar man frågorna som ställs.",
  "Gissar att han dragit hem till Stockholm.",
  "Det var ju det jag sa?",
  "HR tycker han är bättre än AC.",
  "Bra spelare. Inte en superstar men en nyttig truppspelare.",
  "Menar du att han är klar? Igen?",
  "Vi har hört detta förr",
  "Borde ha städat sitt kontor för längesen",
  "Känns som en bra truppspelare att kunna kasta in",
  "Vi lär aldrig få se honom i MFF-tröjan",
  "Är det någon som tycker det är konstigt?",
  "En ny Danne kanske",
  "HRs gamla gullegris",
  "Om han varit 19 hade han varit värd 100 miljoner",
  "Vi behöver inte fler frågetecken",
  "Snart är hela laget ifrån Norrköping",
  "Det här känns inte så genomtänkt",
  "Vem är ens ansvarig?",
  "Kaosvärvning",
  "Allt är ett stort jäkla skämt",
  "Bra scoutat",
  "Vad har hänt egentligen?",
  "Finns ingen långsiktighet",
  "Hur tänkte man här?",
  "Han är inte dålig",
  "Men han är heller inte bra",
  "Vi vinner väl CL snart också",
  "Samma gamla MFF",
  "Men visst, hoppas man har fel",
  "Det är en intressant värvning",
  "Vad händer med våra egna talanger?",
  "Ge mig kardan ;-)",
  "Stabil retorik. Vuxna djupa tankar.",
  "Ska han städa kontoret nu?",
  "Kanske HR sabbar med flit för att behålla dem",
  "Allt är möjligt i vår klubb",
  "När får vi se HR spela själv?",
  "Han duckar som vanligt",
  "Inte direkt ett framtidsnamn",
  "Måste man förstå allt?",
  "HR-logik",
  "Klart vi vinner serien också",
  "Gillar hur han spelar",
  "Rydström ville ha honom",
  "Ingen annan klubb ville ha honom",
  "Han hade sin peak 2020",
  "Får hoppas han blommar ut",
  "Snälla, inte ännu en gubbe från Peking",
  "Hade en bra säsong för fyra år sen",
  "Rydström-effekten är över",
  "Vi värvar bakåt i tiden",
  "Klart han går före Nanasi",
  "Vad sänder detta för signaler?",
  "Det är så typiskt oss",
  "HR vet bäst",
  "Men det är klart",
  "Vi bygger för framtiden",
  "Ingen fara, vi har HR",
  "Välkommen till MFF",
  "En till sopa in",
  "Helt otroligt",
  "Man tappar orden",
  "Nä men perfekt ju",
  "En ny nivå av inkompetens",
  "Det är tragikomiskt",
  "Jag orkar inte mer",
  "Säger mer om HR än om spelaren",
  "Ingen rök utan eld",
  "Varför får han chansen?",
  "HR måste bort",
  "Vi gräver vår egen grav",
  "En sopa till samlingen",
  "Vad fan är det som händer?",
  "Ärkesopan är tillbaka",
  "Vi har inte lärt oss ett skit",
  "Bara att lägga ner",
  "Han är inte ens dålig – bara meningslös",
  "Kolla hans highlights från 2019",
  "Han peakade på Friends",
  "Vi bygger ett nostalgilag",
  "Grattis AIK",
  "Perfekt värvning för 2018",
];

module.exports = {
  forumTexter,
};
